# Funding options for LaraH5P project

github: [musabAlzoubi]  # GitHub Sponsors username
# patreon: musabAlzoubi  # Patreon username
# open_collective: larah5p  # Open Collective username
# ko_fi: musabAlzoubi  # Ko-fi username
# tidelift: packagist/larah5p  # Tidelift package reference
# community_bridge: larah5p  # Community Bridge project
# liberapay: musabAlzoubi  # Liberapay username
# issuehunt: larah5p  # IssueHunt project name
# otechie: musabAlzoubi  # Otechie username
# custom:
#   - 'https://www.buymeacoffee.com/musabAlzoubi'  # BuyMeACoffee link
#   - 'https://donate.stripe.com/larah5p'  # Stripe donations
